<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="dist\" />
    <Folder Include="modules\" />
    <Folder Include="assets\" />
    <Folder Include="src\images\" />
    <Folder Include="src\css\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
